"""Measure a chapter and write CALIBRATION/<chapter>.md.

Every number in that file is generated here, never typed by hand — the same
principle `manifest.json` follows for the stage-by-stage audit trail. Run it
after any stage whose output changed (CLAUDE.md says so explicitly); it does
not gate anything itself, it only reports what the chapter currently looks
like so a stale figure never gets carried in someone's head.

Usage:
    python3 CALIBRATION/calibrate.py chapters/physics-12-1
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from pipeline import mdio  # noqa: E402

# Preference order: the most-processed chapter markdown still on disk is the
# one that reflects the current state of the pipeline for this chapter. Each
# stem may exist as one or both languages - whichever are present get merged.
CHAPTER_MD_STEM_CANDIDATES = [
    "06_simplify/chapter.simplified",
    "05_verify/chapter.verified",
    "04_combined/combined",
    "02_extract/chapter",
]


def _find_chapter_md(chapter_dir: Path):
    for stem in CHAPTER_MD_STEM_CANDIDATES:
        en_path = chapter_dir / f"{stem}.en.md"
        hi_path = chapter_dir / f"{stem}.hi.md"
        if en_path.exists() or hi_path.exists():
            en_chapter = mdio.markdown_to_chapter(en_path.read_text(encoding="utf-8"), "en") if en_path.exists() else None
            hi_chapter = mdio.markdown_to_chapter(hi_path.read_text(encoding="utf-8"), "hi") if hi_path.exists() else None
            rel = stem + (".en.md" if en_path.exists() else "") + ("+" if en_path.exists() and hi_path.exists() else "") + (".hi.md" if hi_path.exists() else "")
            return mdio.merge_by_id(en_chapter, hi_chapter), rel
    return None, None


def _fmt_list(items: list[str], limit: int = 20) -> str:
    if not items:
        return "(none)"
    shown = items[:limit]
    more = f" … +{len(items) - limit} more" if len(items) > limit else ""
    return ", ".join(shown) + more


def calibrate(chapter_dir: Path) -> str:
    lines: list[str] = []
    lines.append(f"# Calibration — `{chapter_dir.name}`")
    lines.append("")
    lines.append("Generated by `CALIBRATION/calibrate.py` — every number below is")
    lines.append("measured, never typed. Re-run after any stage whose output changed.")
    lines.append("")

    chapter, rel = _find_chapter_md(chapter_dir)
    if chapter is None:
        lines.append("No chapter markdown found yet (checked 06_simplify, 05_verify, "
                      "04_combined, 02_extract) — run stages 1–2 first.")
        return "\n".join(lines) + "\n"

    lines.append(f"**Source:** `{rel}` ({len(chapter.items)} items)")
    lines.append("")

    # --- item counts ---
    by_kind: dict[str, int] = {}
    for item in chapter.items:
        by_kind[item.kind] = by_kind.get(item.kind, 0) + 1
    total_parts = sum(len(i.parts) for i in chapter.items)
    total_figures = sum(len(i.figures) for i in chapter.items)
    verified_count = sum(1 for i in chapter.items if i.verified)
    simplified_count = sum(1 for i in chapter.items if i.simplified)
    total_corrections = sum(i.corrections_applied for i in chapter.items)

    lines.append("## Item counts")
    lines.append("")
    for kind in ("example", "exercise", "additional_exercise"):
        if kind in by_kind:
            lines.append(f"- {kind}: {by_kind[kind]}")
    lines.append(f"- parts (sub-items): {total_parts}")
    lines.append(f"- figures: {total_figures}")
    lines.append(f"- verified: {verified_count}/{len(chapter.items)}")
    lines.append(f"- simplified: {simplified_count}/{len(chapter.items)}")
    lines.append(f"- corrections applied so far: {total_corrections}")
    lines.append("")

    # --- bilingual coverage ---
    missing_en_q = [i.id for i in chapter.items if not i.question.en]
    missing_hi_q = [i.id for i in chapter.items if not i.question.hi]
    lines.append("## Bilingual coverage — question text")
    lines.append("")
    lines.append(f"- missing English: {len(missing_en_q)} — {_fmt_list(missing_en_q)}")
    lines.append(f"- missing Hindi: {len(missing_hi_q)} — {_fmt_list(missing_hi_q)}")
    lines.append("")

    # --- Rule 5 (nothing invented): empty solutions must stay visible ---
    def _is_empty_solution(item) -> bool:
        if item.parts:
            return all(not p.solution.en and not p.solution.hi for p in item.parts)
        return not item.solution.en and not item.solution.hi

    empty_solution = [i.id for i in chapter.items if _is_empty_solution(i)]
    empty_final_answer = [
        i.id for i in chapter.items
        if not i.final_answer.en and not i.final_answer.hi
        and not any(p.final_answer.en or p.final_answer.hi for p in i.parts)
    ]
    lines.append("## Empty fields (Rule 5 — must stay visible, never silently filled)")
    lines.append("")
    lines.append(f"- items with no solution at all: {len(empty_solution)} — {_fmt_list(empty_solution)}")
    lines.append(f"- items with no final answer at all: {len(empty_final_answer)} — {_fmt_list(empty_final_answer)}")
    lines.append("")

    # --- manifest.json summary ---
    manifest_path = chapter_dir / "manifest.json"
    lines.append("## Stage history (`manifest.json`)")
    lines.append("")
    if not manifest_path.exists():
        lines.append("No manifest.json yet.")
    else:
        entries = json.loads(manifest_path.read_text(encoding="utf-8"))
        stages_run = sorted({e["stage"] for e in entries})
        total_model_calls = sum(e.get("model_calls", 0) for e in entries)
        ever_failed = sorted({
            gate for e in entries for gate in e.get("gates_failed", {})
        })
        lines.append(f"- entries: {len(entries)}")
        lines.append(f"- stages run at least once: {', '.join(stages_run) or '(none)'}")
        lines.append(f"- total model calls across all entries: {total_model_calls}")
        if ever_failed:
            lines.append(f"- gates that have failed at some point: {', '.join(ever_failed)}")
        else:
            lines.append("- no gate has ever failed for this chapter")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    if len(sys.argv) != 2:
        print("usage: python3 CALIBRATION/calibrate.py <chapter-dir>", file=sys.stderr)
        raise SystemExit(2)

    chapter_dir = Path(sys.argv[1]).resolve()
    if not chapter_dir.is_dir():
        print(f"not a directory: {chapter_dir}", file=sys.stderr)
        raise SystemExit(1)

    report = calibrate(chapter_dir)
    out_path = Path(__file__).resolve().parent / f"{chapter_dir.name}.md"
    out_path.write_text(report, encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
